python mel.py ./sep_files/sep_0.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_1.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_10.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_100.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_101.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_102.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_103.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_104.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_105.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_106.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_107.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_108.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_109.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_11.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_110.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_111.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_112.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_113.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_114.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_115.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_116.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_117.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_118.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_119.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_12.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_120.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_121.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_122.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_123.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_124.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_125.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_126.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_127.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_128.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_129.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_13.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_130.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_131.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_132.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_133.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_134.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_135.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_136.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_137.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_138.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_139.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_14.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_140.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_141.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_142.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_143.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_144.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_145.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_146.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_147.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_148.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_149.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_15.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_150.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_151.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_152.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_153.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_154.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_155.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_156.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_157.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_158.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_159.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_16.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_160.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_161.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_162.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_163.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_164.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_165.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_166.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_167.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_168.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_169.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_17.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_170.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_171.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_172.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_173.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_174.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_175.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_176.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_177.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_178.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_179.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_18.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_180.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_181.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_182.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_183.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_184.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_185.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_186.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_187.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_188.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_189.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_19.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_190.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_191.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_2.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_20.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_21.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_22.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_23.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_24.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_25.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_26.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_27.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_28.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_29.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_3.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_30.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_31.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_32.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_33.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_34.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_35.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_36.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_37.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_38.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_39.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_4.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_40.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_41.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_42.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_43.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_44.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_45.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_46.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_47.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_48.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_49.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_5.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_50.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_51.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_52.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_53.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_54.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_55.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_56.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_57.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_58.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_59.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_6.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_60.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_61.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_62.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_63.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_64.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_65.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_66.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_67.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_68.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_69.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_7.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_70.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_71.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_72.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_73.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_74.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_75.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_76.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_77.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_78.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_79.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_8.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_80.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_81.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_82.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_83.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_84.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_85.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_86.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_87.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_88.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_89.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_9.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_90.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_91.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_92.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_93.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_94.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_95.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_96.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_97.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_98.wav ./sep_files/ plot ./mel_img/
python mel.py ./sep_files/sep_99.wav ./sep_files/ plot ./mel_img/
